config/routes.rb
Rails.application.routes.draw do
  root "task_lists#index"
  get "signin" => "sessions#new", as: :signin
  post "signin" => "sessions#create"
  get "signout" => "sessions#destroy", as: :signout

  resources :task_lists, only: [] do
    resources :tasks
  end

  resources :tasks, only: [] do
    resources :comments do
      resources :comments
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :task
  belongs_to :user
  belongs_to :comment
  has_many :comments

end

app/models/task.rb
class Task < ActiveRecord::Base

  belongs_to :task_list
  has_many :comments
  belongs_to :user, foreign_key: "assigned_to"
  validates_presence_of :description

  scope :incomplete, -> { where(completed: false) }

end

app/models/task_list.rb
class TaskList < ActiveRecord::Base

  has_many :tasks

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :email, presence: true, uniqueness: {case_sensitive: false}
  validates :name, presence: true, uniqueness: {case_sensitive: false}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :ensure_current_user

  def ensure_current_user
    redirect_to signin_path unless current_user
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  helper_method :current_user

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @task = Task.find(params[:task_id])
    @comment = Comment.new
  end

  def create
    @task = Task.find(params[:task_id])
    @comment = Comment.new(params.require(:comment).permit(:body))
    @comment.task = @task
    @comment.user = current_user
    @comment.save
    redirect_to root_path

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_current_user

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: params[:user][:email])
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      @user = User.new(email: params[:user][:email])
      @user.errors[:base] << "Username / password is invalid"
      render :new
    end
  end

  def destroy
    session.destroy
    redirect_to signin_path
  end

end

app/controllers/task_lists_controller.rb
class TaskListsController < ApplicationController

  def index
    if params[:task]
      @assigned_to = params[:task][:assigned_to]
    end

    @task_lists = TaskList.order(:name)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :find_task_list

  def new
    @task = Task.new
  end

  def index
  end

  def edit
    @task_list = TaskList.find(params[:task_list_id])
    @task = Task.find(params[:id])
  end

  def create
    @task = @task_list.tasks.new(params.require(:task).permit(:description, :due_date, :assigned_to))
    if @task.save
      redirect_to root_path, notice: "Task was created successfully!"
    else
      render :new
    end
  end

  def update
    @task = @task_list.tasks.find(params[:id])
    @task.update_attributes(completed: true)
    redirect_to root_path, notice: "Task was completed successfully!"
  end


  private

  def find_task_list
    @task_list = TaskList.find(params[:task_list_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<%= comment.user.name %>
<%= comment.body %>
<%= comment.created_at %>

app/views/comments/new.html.erb
<h2>Add Comment</h2>

<%= form_for [@task, @comment] do |f| %>
  <%= hidden_field_tag :comment_id, params[:comment_id] %>
  <%= f.label :body %>
  <%= f.text_field :body %>
  <br>
  <br>
  <%= f.submit %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails Practice</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <div class="container">
    <div class="logo">
      <%= link_to "Rails Practice", root_path %>
    </div>
    <% if current_user %>
      <div class="logout">
        <%= current_user.email %> |
        <%= link_to "Logout", signout_path %>
      </div>
    <% end %>
  </div>
</header>
<main>
  <div class="container">
    <% if notice %>
      <div class="flash notice"><%= notice %></div>
    <% end %>
    <%= yield %>
  </div>
</main>
</body>
</html>

app/views/task_lists/index.html.erb
<%= form_tag('/', method: :get) do %>
  <%= collection_select(:task, :assigned_to, User.all, :id, :name, include_user: "Select User") %>
  <%= submit_tag "Filter" %>
<% end %>

<% @task_lists.each do |task_list| %>

  <section class="task-list">
    <%= link_to "+ Add Task", new_task_list_task_path(task_list), class: "add-task" %>
    <h1><%= task_list.name %></h1>
    <% tasks = task_list.tasks.incomplete.order(:due_date) %>
    <% if @assigned_to %>
      <% tasks = tasks.where(:assigned_to => @assigned_to) %>
    <% end %>
    <% if tasks.present? %>
      <%= render partial: 'tasks/task', collection: tasks %>
    <% else %>
      <div class="empty">Nothing here to see!</div>
    <% end %>
<% end %>
</section>

app/views/tasks/_form.html.erb
<%= form_for [@task_list, @task], html: { class: "task-form" } do |f| %>


  <% if f.object.errors.any? %>
    <div class="error">Your task could not be created</div>
  <% end %>

  <div class="form-row">
    <%= f.label :description, class: "form-label" %>
    <%= f.text_field :description %>
  </div>

  <div class="form-row">
    <%= f.label :due_date, class: "form-label" %>
    <%= f.date_select :due_date %>
  </div>

  <div class="form-rom">
    <%= f.label :assigned_to, class: "form-label" %>
    <%= f.collection_select :assigned_to, User.order(:name), :id, :name, include_blank: "Select a user" %>
  </div>

  <div class="form-row">
    <%= f.submit %>
  </div>

<% end %>

app/views/tasks/_task.html.erb
<div class="task">
  <%= form_for [task.task_list, task] do |f| %>
    <%= f.submit "Complete", class: "complete-button" %>

  <% end %>
  <span class="task-description"><%= link_to task.description, edit_task_list_task_path(task.task_list, task) %></span>
  <span class="task-due">
    (<%= distance_of_time_in_words(Time.now, task.due_date + 1.day) %>)
  </span>


  <% if task.user %>
    <%= task.user.name %>
  <% end %>
  <%= link_to "Comment", new_task_comment_path(task) %>

  <%= render task.comments %>
</div>

app/views/tasks/edit.html.erb
<h2>Edit this task</h2>

<%= render 'form' %>

app/views/tasks/new.html.erb
<h2>Add a Task</h2>
<%= render 'form' %>